name: "Deploy"

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install deps
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Deploy
        run: pnpm run deploy
